/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { Examination } from "./Examination";
import { ExaminationCountArgs } from "./ExaminationCountArgs";
import { ExaminationFindManyArgs } from "./ExaminationFindManyArgs";
import { ExaminationFindUniqueArgs } from "./ExaminationFindUniqueArgs";
import { DeleteExaminationArgs } from "./DeleteExaminationArgs";
import { ExaminationService } from "../examination.service";
@graphql.Resolver(() => Examination)
export class ExaminationResolverBase {
  constructor(protected readonly service: ExaminationService) {}

  async _examinationsMeta(
    @graphql.Args() args: ExaminationCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [Examination])
  async examinations(
    @graphql.Args() args: ExaminationFindManyArgs
  ): Promise<Examination[]> {
    return this.service.examinations(args);
  }

  @graphql.Query(() => Examination, { nullable: true })
  async examination(
    @graphql.Args() args: ExaminationFindUniqueArgs
  ): Promise<Examination | null> {
    const result = await this.service.examination(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Examination)
  async deleteExamination(
    @graphql.Args() args: DeleteExaminationArgs
  ): Promise<Examination | null> {
    try {
      return await this.service.deleteExamination(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
