/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { Finance } from "./Finance";
import { FinanceCountArgs } from "./FinanceCountArgs";
import { FinanceFindManyArgs } from "./FinanceFindManyArgs";
import { FinanceFindUniqueArgs } from "./FinanceFindUniqueArgs";
import { DeleteFinanceArgs } from "./DeleteFinanceArgs";
import { FinanceService } from "../finance.service";
@graphql.Resolver(() => Finance)
export class FinanceResolverBase {
  constructor(protected readonly service: FinanceService) {}

  async _financesMeta(
    @graphql.Args() args: FinanceCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [Finance])
  async finances(
    @graphql.Args() args: FinanceFindManyArgs
  ): Promise<Finance[]> {
    return this.service.finances(args);
  }

  @graphql.Query(() => Finance, { nullable: true })
  async finance(
    @graphql.Args() args: FinanceFindUniqueArgs
  ): Promise<Finance | null> {
    const result = await this.service.finance(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Finance)
  async deleteFinance(
    @graphql.Args() args: DeleteFinanceArgs
  ): Promise<Finance | null> {
    try {
      return await this.service.deleteFinance(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
